[project]
name = "sign-detector"
version = "0.1.0"
description = "A sign detector built with Mediapipe and OpenCV."
requires-python = ">=3.12"
dependencies = [
  "opencv-python-headless==4.9.0.80",
  "mediapipe==0.10.18",
  "numpy>=1.26",
  "websocket-client==1.9.0",
  "python-dotenv==1.2.2"
]

[dependency-groups]
dev = [
    "ruff>=0.15.10",
]